"""changed the column name from is_deleted to is_deactivated

Revision ID: 1579890df59b
Revises: 1592d8d8d768
Create Date: 2024-11-21 12:28:55.885630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1579890df59b'
down_revision = '1592d8d8d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_details', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    op.add_column('professional_details', sa.Column('deactivate_at', sa.DateTime(), nullable=True))
    op.drop_column('professional_details', 'deleted_at')
    op.drop_column('professional_details', 'is_deleted')
    op.add_column('service', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    op.add_column('service', sa.Column('deactivate_at', sa.DateTime(), nullable=True))
    op.drop_column('service', 'deleted_at')
    op.drop_column('service', 'is_deleted')
    op.add_column('service_request', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    op.add_column('service_request', sa.Column('deactivate_at', sa.DateTime(), nullable=True))
    op.drop_column('service_request', 'deleted_at')
    op.drop_column('service_request', 'is_deleted')
    op.add_column('user', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deactivate_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'deactivate_at')
    op.drop_column('user', 'is_deactivated')
    op.add_column('service_request', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('service_request', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.drop_column('service_request', 'deactivate_at')
    op.drop_column('service_request', 'is_deactivated')
    op.add_column('service', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('service', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.drop_column('service', 'deactivate_at')
    op.drop_column('service', 'is_deactivated')
    op.add_column('professional_details', sa.Column('is_deleted', sa.BOOLEAN(), nullable=True))
    op.add_column('professional_details', sa.Column('deleted_at', sa.DATETIME(), nullable=True))
    op.drop_column('professional_details', 'deactivate_at')
    op.drop_column('professional_details', 'is_deactivated')
    # ### end Alembic commands ###
