"""add avg_rating for professional

Revision ID: 3a4c5fcecd5d
Revises: 1579890df59b
Create Date: 2024-11-25 22:17:10.713335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4c5fcecd5d'
down_revision = '1579890df59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_details', sa.Column('avg_rating', sa.Float(), nullable=True))
    op.drop_column('professional_details', 'is_approved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_details', sa.Column('is_approved', sa.BOOLEAN(), nullable=True))
    op.drop_column('professional_details', 'avg_rating')
    # ### end Alembic commands ###
