"""Issue realted column added to service request

Revision ID: ad6238bb2870
Revises: 3a4c5fcecd5d
Create Date: 2024-11-26 11:27:04.357189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6238bb2870'
down_revision = '3a4c5fcecd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_request', sa.Column('cust_issue_raised', sa.Boolean(), nullable=True))
    op.add_column('service_request', sa.Column('prof_issue_raised', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_request', 'prof_issue_raised')
    op.drop_column('service_request', 'cust_issue_raised')
    # ### end Alembic commands ###
